### ISSUE TITLE
Page templater for CPT

### ISSUE THREAD

**Issue by klihelp** [wpexplorer/page-templater#1]
How to make it work with Custom Post Types?

**Comment by jeanpierreb** [comment]
@klihelp you may want to explore post formats instead for this purpose

**Comment by wpexplorer** [comment]
This should work ion 4.7 though - https://github.com/wpexplorer/page-templater/issues/5

**Comment by klihelp** [comment]
Post type templates feature built into WordPress 4.7.
https://core.trac.wordpress.org/ticket/18375

**Comment by wpexplorer** [comment]
@klihelp - Yep ;)
