### ISSUE TITLE
Cannot get to work. Add_action placement?

### ISSUE THREAD

**Issue by tim-rohrer** [wpexplorer/page-templater#16]
Hi.

I'm using WP 4.9.2, and am developing a plugin using the Wordpress Plugin Boilerplate.  Because the Boilerplate handles all `add_action` statements with a helper function, I found I had to not use an array to pass the class and method. Instead of `add_action( 'plugins_loaded', array( 'PageTemplater', 'get_instance' ) );` I am using:  `$this->loader->add_action( 'plugins_loaded', $plugin_admin, 'PageTemplater::get_instance' );`

But, I'm getting an error about class hierarchy: `( ! ) Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Home_Search_Admin' is not a subclass of 'PageTemplater' in /var/www/html/wp-includes/class-wp-hook.php on line 286`

1) Does using the array in the `add_action` cause something to be handled differently that how I've done things? 
2) Where does the `add_action` need to be placed in the plugin code (i.e., really really early)?

**Comment by tim-rohrer** [comment]
Never mind. I think I see what I'm missing.

**Comment by jarimos** [comment]
I am deprecated... 2 years cleanning stairs is my job...sorry...good luck
:-)

Den 19/01/2018 9.36 PM skrev "tim.rohrer" <notifications@github.com>:
