### ISSUE TITLE
Template Has to be Reset With New Code Deployment

### ISSUE THREAD

**Issue by donaldG** [wpexplorer/page-templater#20]
Hi! I'm picking up where another dev left off on a project and noticed he used this plugin/code. Curiously, every time I run a deployment of new code the template is dropped from the page in question and I have to go select it again. Any idea what might be going on with that? Thanks in advance!

**Comment by jarimos** [comment]
No. I am not working with code anymore...

**Comment by wpexplorer** [comment]
@donaldG - you'll need to be a bit more specific with what you are doing exactly when you say "run a deployment of new code" - this is an extremely vague statement.

**Comment by donaldG** [comment]
Sorry about that vagueness. We use Github to version control our workflow and Capistrano to deploy code from Github to our different environments (dev/stage/production/etc.). Anytime we deploy code to one of these environments, let's just say stage, and the old code is overwritten and I have to go select the template again. That help?

**Comment by donaldG** [comment]
Closing! Discovered it's a pathing issue, it wants to point to the template in each release instead of a relative path back to the plugin. No sweat on my end now, sorry for the bother!
