### ISSUE TITLE
Not working with WordPress v4.7

### ISSUE THREAD

**Issue by WPDevHQ** [wpexplorer/page-templater#5]
I'm using this code in one of my plugins and works perfectly with the current version of WordPress.

Unfortunately it will no longer work with the upcomig v4.7 due to the changes they have made to accommodate post type templates.

I'm trying to figure it out but so far I'm just tearing my hair out!

**Comment by leeb003** [comment]
I saw that too.  So, it looks like we can correct it with just a few lines of code.  
If you replace lines 43 through 47 with a version check...
`        // Add a filter to the attributes metabox to inject template into the cache.
        if ( version_compare( floatval($GLOBALS['wp_version']), '4.7', '<' ) ) { // 4.6 and older
            add_filter(
                'page_attributes_dropdown_pages_args',
                array( $this, 'register_project_templates' )
            );
        } else { // Add a filter to the wp 4.7 version attributes metabox
            add_filter(
                'theme_page_templates', array( $this, 'add_new_template' )
            );
        }
`
Then add the simple function to use for version 4.7 up...
`
    /**
     * Adds our template to the page dropdown for v4.7+
     *
     **/
    public function add_new_template( $posts_templates ) {
        $posts_templates = array_merge( $posts_templates, $this->templates );
        return $posts_templates;
    }
`
It works for me, here's the page I referenced for some more info on the changes https://make.wordpress.org/core/2016/11/03/post-type-templates-in-4-7/

**Comment by wpexplorer** [comment]
Looks great @leeb003 - if you want to submit a pull request for this, please do.

**Comment by leeb003** [comment]
Hey wpexplorer,
I created a fork and committed the changes to it.  I think that's the right way - let me know if that works.

Lee

**Comment by WPDevHQ** [comment]
This worked perfectly.

Thank you @leeb003 for the solution.

**Comment by wpexplorer** [comment]
Thank you @leeb003 for the pull-request and fixes.
